from __future__ import annotations
from typing import Protocol
from app.tenancy.models import User, Client

class Repository(Protocol):
    def get_user_by_email(self, email: str) -> User | None: ...
    def get_user_by_id(self, user_id: str) -> User | None: ...
    def list_clients(self) -> list[Client]: ...
    def get_client(self, client_id: str) -> Client | None: ...
