from __future__ import annotations
from app.tenancy.models import User, Client, Role

def row_to_user(row: dict) -> User:
    return User(
        id=str(row["id"]), email=row["email"], password_hash=row["password_hash"],
        role=Role(row["role"]), client_id=row.get("client_id"), active=row.get("active", True),
        # Absent on a database that has not had the migration applied yet -> False,
        # i.e. nobody is forced to change a password they were never given.
        must_change_password=bool(row.get("must_change_password", False)),
    )

def row_to_client(row: dict) -> Client:
    return Client(
        id=row["id"], name=row["name"], provider=row["provider"],
        provider_config=row.get("provider_config") or {}, active=row.get("active", True),
    )

class SupabaseRepository:
    """Production repository backed by supabase-py. Constructed with a supabase client."""
    def __init__(self, client) -> None:
        self._c = client

    def get_user_by_email(self, email: str) -> User | None:
        res = self._c.table("users").select("*").eq("email", email).limit(1).execute()
        rows = res.data or []
        return row_to_user(rows[0]) if rows else None

    def get_user_by_id(self, user_id: str) -> User | None:
        res = self._c.table("users").select("*").eq("id", user_id).limit(1).execute()
        rows = res.data or []
        return row_to_user(rows[0]) if rows else None

    def list_clients(self) -> list[Client]:
        res = self._c.table("clients").select("*").eq("active", True).execute()
        return [row_to_client(r) for r in (res.data or [])]

    def get_client(self, client_id: str) -> Client | None:
        res = self._c.table("clients").select("*").eq("id", client_id).limit(1).execute()
        rows = res.data or []
        return row_to_client(rows[0]) if rows else None

    # --- provisioning writes -------------------------------------------------

    def create_user(
        self,
        *,
        email: str,
        password_hash: str,
        role: Role,
        client_id: str | None,
        must_change_password: bool = False,
    ) -> User:
        # Pre-check rather than relying on the unique index: a constraint violation
        # surfaces as an opaque 500, and the caller wants a PT-BR 422.
        if self.get_user_by_email(email) is not None:
            raise ValueError(f"e-mail já cadastrado: {email}")
        res = (
            self._c.table("users")
            .insert(
                {
                    "email": email,
                    "password_hash": password_hash,
                    "role": role.value,
                    "client_id": client_id,
                    "active": True,
                    "must_change_password": must_change_password,
                }
            )
            .execute()
        )
        rows = res.data or []
        if not rows:
            raise ValueError("falha ao criar o usuário")
        # `id` is generated by Postgres (gen_random_uuid()), so read it back.
        return row_to_user(rows[0])

    def list_users_for_client(self, client_id: str) -> list[User]:
        # No `.eq("active", True)`: the UI must show deactivated users too.
        res = self._c.table("users").select("*").eq("client_id", client_id).execute()
        return [row_to_user(r) for r in (res.data or [])]

    def set_user_active(self, user_id: str, active: bool) -> User | None:
        res = (
            self._c.table("users")
            .update({"active": active})
            .eq("id", user_id)
            .execute()
        )
        rows = res.data or []
        return row_to_user(rows[0]) if rows else None

    def set_password(
        self, user_id: str, password_hash: str, *, must_change_password: bool = False
    ) -> User | None:
        res = (
            self._c.table("users")
            .update(
                {
                    "password_hash": password_hash,
                    "must_change_password": must_change_password,
                }
            )
            .eq("id", user_id)
            .execute()
        )
        rows = res.data or []
        return row_to_user(rows[0]) if rows else None

    def create_client(
        self, *, id: str, name: str, provider: str, provider_config: dict | None = None
    ) -> Client:
        if self.get_client(id) is not None:
            raise ValueError(f"cliente já existe: {id}")
        res = (
            self._c.table("clients")
            .insert(
                {
                    "id": id,
                    "name": name,
                    "provider": provider,
                    "provider_config": provider_config or {},
                    "active": True,
                }
            )
            .execute()
        )
        rows = res.data or []
        if not rows:
            raise ValueError("falha ao criar o cliente")
        return row_to_client(rows[0])
