"""Regenerate base_resultado_layout.py from the ground-truth workbook TSV dump.

Run from the repo root:
    .venv/bin/python mbc-automation/backend/scripts/gen_base_resultado_layout.py

Source of truth: work/analysis/fechamento_values/Base_Resultado_Mensal_V2.tsv
(a verbatim dump of the original workbook's values, used only at build time to
fix the line labels/order — never at request time).
"""
from __future__ import annotations

import pprint
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
TSV = REPO_ROOT / "work/analysis/fechamento_values/Base_Resultado_Mensal_V2.tsv"
OUT = REPO_ROOT / "mbc-automation/backend/mbc_automation/base_resultado_layout.py"

TOTAL_LABELS = {
    "Custo equipe - Contencioso", "Custo equipe - Econômico",
    "Custo equipe - Arbitragem e Compliance", "Despesas para Clientes",
    "Ocupação", "Despesas Gerais", "Consultoria", "Salários Administração",
    "Administrativas", "Taxas / Despesas Financeiras",
    "Investimentos em Prospecção", "Gestão do Conhecimento", "Endomarketing",
    "Impostos", "Informática", "Distribuição de Lucros extras", "Total saídas",
    "Telecomunicações",
}


def classify(line_no: int, label: str) -> tuple[str, bool]:
    if line_no == 4 and label.startswith("Receita de honor"):
        return "api", False
    if line_no == 3:
        return "formula", False
    norm = label.rstrip().rstrip("\u00a0").strip()
    if norm in TOTAL_LABELS:
        return "formula", True
    return "manual", False


def main() -> None:
    rows = []
    with TSV.open() as f:
        for i, raw in enumerate(f, start=1):
            cols = raw.rstrip("\n").split("\t")
            rows.append((i, cols[0].strip() if cols else ""))

    entries = []
    for line_no, label in rows:
        if line_no < 3 or line_no > 192 or not label:
            continue
        source, is_total = classify(line_no, label)
        indent = 0 if (is_total or line_no in (3, 4)) else 1
        entries.append({
            "row": line_no, "label": label, "source": source,
            "is_total": is_total, "indent": indent,
        })

    header = (
        '"""1:1 line layout for the ``Base_Resultado Mensal_V2`` tab.\n\n'
        "Auto-generated by scripts/gen_base_resultado_layout.py from the ground-truth\n"
        "workbook dump. Each line is classified by data source (api/formula/manual).\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        "BASE_RESULTADO_LINES: list[dict] = "
    )
    OUT.write_text(header + pprint.pformat(entries, indent=4, sort_dicts=False, width=120) + "\n")
    print(f"wrote {OUT} with {len(entries)} lines")


if __name__ == "__main__":
    main()
