-- Hunt: the convênio memo arithmetic MUST have a DB source. The ledger says
-- RB Mar+: 8.579,33 - 6.053,24 = 2.526,09  |  EHF Mar+: 3.520,31 - 1.956,21 = 1.564,10
-- These invoice-scale numbers (8k, 6k, 3.5k, 1.9k) should appear SOMEWHERE if
-- they exist in the DB at all. Read-only, brute-force search.
SET DEFINE OFF
SET PAGESIZE 400
SET LINESIZE 340
SET FEEDBACK ON
COL prof FORMAT A6
COL conta FORMAT A20
COL hist FORMAT A80
WHENEVER SQLERROR CONTINUE

PROMPT === 1. Any LANCAMENTO row Feb..Mai with value NEAR the memo numbers (any account) ===
SELECT l.PCTCNUMEROCONTADEST conta, l.LANCPROFDEST prof,
       ROUND(l.LANNVALOR,2) net, TO_CHAR(l.LANDDATA,'YYYY-MM') mes,
       SUBSTR(l.LANCHISTORICO,1,60) hist
  FROM FINANCE.LANCAMENTO l
 WHERE l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-06-01'
   AND (ABS(l.LANNVALOR-8579.33) < 1 OR ABS(l.LANNVALOR-6053.24) < 1
        OR ABS(l.LANNVALOR-3520.31) < 1 OR ABS(l.LANNVALOR-1956.21) < 1
        OR ABS(l.LANNVALOR-1192.36) < 1 OR ABS(l.LANNVALOR-1795.86) < 1)
 ORDER BY l.LANDDATA;

PROMPT === 2. Any CONTASPAGAR row with value near the memo numbers, Feb..Mai ===
SELECT cp.PCTCNUMEROCONTA conta, cp.COD_ADVG prof,
       ROUND(cp.CPGNVALORBASE,2) base, TO_CHAR(cp.CPGDVECTO,'YYYY-MM') mes,
       SUBSTR(cp.CPGCHISTORICO,1,60) hist
  FROM FINANCE.CONTASPAGAR cp
 WHERE cp.CPGDVECTO >= DATE '2026-02-01' AND cp.CPGDVECTO < DATE '2026-06-01'
   AND (ABS(cp.CPGNVALORBASE-8579.33) < 1 OR ABS(cp.CPGNVALORBASE-6053.24) < 1
        OR ABS(cp.CPGNVALORBASE-3520.31) < 1 OR ABS(cp.CPGNVALORBASE-1956.21) < 1)
 ORDER BY cp.CPGDVECTO;

PROMPT === 3. Full RB movements ALL accounts Feb (find the missing pieces) ===
SELECT l.PCTCNUMEROCONTADEST conta, ROUND(l.LANNVALOR,2) net,
       SUBSTR(l.LANCHISTORICO,1,70) hist
  FROM FINANCE.LANCAMENTO l
 WHERE (l.LANCPROFDEST='RB' OR l.COD_ADVG='RB'
        OR l.LANCHISTORICO LIKE '%RB%' AND l.LANCHISTORICO LIKE '%onv%')
   AND l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01'
 ORDER BY conta;

PROMPT === 4. Full EHF movements ALL accounts Feb ===
SELECT l.PCTCNUMEROCONTADEST conta, ROUND(l.LANNVALOR,2) net,
       SUBSTR(l.LANCHISTORICO,1,70) hist
  FROM FINANCE.LANCAMENTO l
 WHERE (l.LANCPROFDEST='EHF' OR l.COD_ADVG='EHF'
        OR l.LANCHISTORICO LIKE '%EHF%' AND l.LANCHISTORICO LIKE '%onv%')
   AND l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01'
 ORDER BY conta;

PROMPT === 5. Sum EHF/RB convênio-related debits (0110 + 500.010.<SIGLA> convênio rows) ===
PROMPT     ledger EHF = 1.564,10   ; ledger RB = 2.526,09
SELECT l.LANCPROFDEST prof, l.PCTCNUMEROCONTADEST conta,
       ROUND(SUM(l.LANNVALOR),2) net
  FROM FINANCE.LANCAMENTO l
 WHERE l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01'
   AND ((l.LANCPROFDEST IN ('EHF','RB') AND l.PCTCNUMEROCONTADEST='030.010.0110')
        OR (l.PCTCNUMEROCONTADEST IN ('500.010.EHF','500.010.RB')
            AND UPPER(l.LANCHISTORICO) LIKE '%CONV%'))
 GROUP BY l.LANCPROFDEST, l.PCTCNUMEROCONTADEST
 ORDER BY prof, conta;

PROMPT === 6. Is 968,65 (EHF Feb memo "Valor 968,65") anywhere? ===
SELECT l.PCTCNUMEROCONTADEST conta, l.LANCPROFDEST prof,
       ROUND(l.LANNVALOR,2) net, SUBSTR(l.LANCHISTORICO,1,70) hist
  FROM FINANCE.LANCAMENTO l
 WHERE l.LANDDATA >= DATE '2026-01-01' AND l.LANDDATA < DATE '2026-06-01'
   AND ABS(l.LANNVALOR-968.65) < 0.5
 ORDER BY l.LANDDATA;

PROMPT === 7. Debit-side JOIN: for each 500.010.EHF convênio row, is there a matching credit? ===
SELECT l.PCTCNUMEROCONTADEST conta_dest, l.PCTCNUMEROCONTAORG conta_org,
       ROUND(l.LANNVALOR,2) net, SUBSTR(l.LANCHISTORICO,1,80) hist
  FROM FINANCE.LANCAMENTO l
 WHERE l.PCTCNUMEROCONTADEST IN ('500.010.EHF','500.010.RB')
   AND l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01';

EXIT
