-- Probe: read the per-professional area-percentage tables found in the dictionary.
-- CAD_RATEIO_GRUPO(ID_PROFISSIONAL, ID_GRUPOJURIDICO, PERCENTUAL, ANO_MES_*) and
-- CAD_RATEIOADVG_HIST(COD_ADVG, ANO_MES, SETOR, PERCENTUAL) are the candidate
-- sources for Aurelio's (AM) 50/50 Contencioso/Econômico split -- the last piece
-- for fully automated per-area Custo equipe. Read-only.
--
-- AM's ID_PROFISSIONAL: resolve from CAD_PROFISSIONAL (sigla 'AM' -> ID). Some
-- installs key CAD_RATEIO_GRUPO by ID_PROFISSIONAL (a GUID), others by sigla.
SET DEFINE OFF
SET PAGESIZE 500
SET LINESIZE 320
SET FEEDBACK ON
WHENEVER SQLERROR CONTINUE

PROMPT === 0. Resolve AM identifiers (sigla -> ID_PROFISSIONAL, home grupo) ===
SELECT SIGLA, ID_PROFISSIONAL, ID_GRUPOJURIDICO, SOCIO
  FROM LDESK.CAD_PROFISSIONAL WHERE SIGLA='AM';

PROMPT === 1. CAD_RATEIO_GRUPO: ALL rows for AM (join grupo name + resolve prof by sigla) ===
SELECT rg.ID_PROFISSIONAL, p.SIGLA, g.NOME AS grupo, rg.PERCENTUAL,
       rg.ANO_MES_INICIAL, rg.ANO_MES_FINAL
  FROM LDESK.CAD_RATEIO_GRUPO rg
  LEFT JOIN LDESK.CAD_PROFISSIONAL p ON p.ID_PROFISSIONAL = rg.ID_PROFISSIONAL
  LEFT JOIN LDESK.CAD_GRUPOJURIDICO g ON g.ID_GRUPOJURIDICO = rg.ID_GRUPOJURIDICO
 WHERE p.SIGLA='AM'
 ORDER BY rg.ANO_MES_INICIAL, g.NOME;

PROMPT === 2. CAD_RATEIO_GRUPO: the FULL table (who is multi-area, with percentages) ===
PROMPT     Active rows only-ish; shows the whole rateio model in one shot.
SELECT p.SIGLA, g.NOME AS grupo, rg.PERCENTUAL,
       rg.ANO_MES_INICIAL, rg.ANO_MES_FINAL
  FROM LDESK.CAD_RATEIO_GRUPO rg
  LEFT JOIN LDESK.CAD_PROFISSIONAL p ON p.ID_PROFISSIONAL = rg.ID_PROFISSIONAL
  LEFT JOIN LDESK.CAD_GRUPOJURIDICO g ON g.ID_GRUPOJURIDICO = rg.ID_GRUPOJURIDICO
 ORDER BY p.SIGLA, g.NOME;

PROMPT === 3. CAD_RATEIOADVG_HIST: AM rows for 2026-02 (COD_ADVG + SETOR + PERCENTUAL) ===
SELECT COD_ADVG, ANO_MES, SETOR, PERCENTUAL, SITUACAO
  FROM SSJR.CAD_RATEIOADVG_HIST
 WHERE COD_ADVG='AM' AND ANO_MES='2026-02'
 ORDER BY SETOR;

PROMPT === 3b. CAD_RATEIOADVG_HIST: AM any month (see the shape/history) ===
SELECT COD_ADVG, ANO_MES, SETOR, PERCENTUAL, SITUACAO
  FROM SSJR.CAD_RATEIOADVG_HIST
 WHERE COD_ADVG='AM'
 ORDER BY ANO_MES, SETOR;

PROMPT === 4. CAD_RATEIOADVG_HIST: full 2026-02 map (all lawyers, sector %s) ===
SELECT COD_ADVG, SETOR, PERCENTUAL
  FROM SSJR.CAD_RATEIOADVG_HIST
 WHERE ANO_MES='2026-02'
 ORDER BY COD_ADVG, SETOR;

PROMPT === 5. Decode SETOR values (what areas do they map to?) ===
SELECT DISTINCT SETOR FROM SSJR.CAD_RATEIOADVG_HIST ORDER BY SETOR;

EXIT
