-- Probe: FIND the monthly AASP (54,35/lawyer) that the ledger books every month
-- for AM and DC but which we could not locate in LANCAMENTO 0110/0150. The
-- catalogue says 0150=AASP; 0160=ISS. AASP only showed up as 0160 in Jan/Apr
-- (quarterly ISS-Trimestral). This is the LAST residual (AM/DC -108,70). Find
-- where AASP lives, and confirm the EHF/RB convênio dependente split. Read-only.
SET DEFINE OFF
SET PAGESIZE 1000
SET LINESIZE 340
SET FEEDBACK ON
COL prof FORMAT A6
COL hist FORMAT A55
COL mes FORMAT A7
WHENEVER SQLERROR CONTINUE

PROMPT === 1. AASP account 030.010.0150 — ANY rows at all, Jan..Mai, any lawyer? ===
SELECT l.LANCPROFDEST prof, TO_CHAR(l.LANDDATA,'YYYY-MM') mes,
       ROUND(SUM(l.LANNVALOR),2) net, COUNT(*) n
  FROM FINANCE.LANCAMENTO l
 WHERE l.PCTCNUMEROCONTADEST='030.010.0150'
   AND l.LANDDATA >= DATE '2026-01-01' AND l.LANDDATA < DATE '2026-06-01'
 GROUP BY l.LANCPROFDEST, TO_CHAR(l.LANDDATA,'YYYY-MM')
 ORDER BY prof, mes;

PROMPT === 2. Any account carrying 54,35 (AASP monthly) for AM, Jan..Mai ===
SELECT l.PCTCNUMEROCONTADEST conta, TO_CHAR(l.LANDDATA,'YYYY-MM') mes,
       ROUND(l.LANNVALOR,2) net, SUBSTR(l.LANCHISTORICO,1,45) hist
  FROM FINANCE.LANCAMENTO l
 WHERE l.LANCPROFDEST='AM'
   AND l.LANDDATA >= DATE '2026-01-01' AND l.LANDDATA < DATE '2026-06-01'
   AND ABS(l.LANNVALOR) BETWEEN 50 AND 120
 ORDER BY mes, conta;

PROMPT === 3. CONTASPAGAR: AASP 0150 gross for AM/DC, Jan..Mai (maybe it's payable-side) ===
SELECT cp.COD_ADVG prof, cp.PCTCNUMEROCONTA conta, TO_CHAR(cp.CPGDVECTO,'YYYY-MM') mes,
       ROUND(SUM(cp.CPGNVALORBASE),2) base
  FROM FINANCE.CONTASPAGAR cp
 WHERE cp.COD_ADVG IN ('AM','DC') AND cp.PCTCNUMEROCONTA='030.010.0150'
   AND cp.CPGDVECTO >= DATE '2026-01-01' AND cp.CPGDVECTO < DATE '2026-06-01'
 GROUP BY cp.COD_ADVG, cp.PCTCNUMEROCONTA, TO_CHAR(cp.CPGDVECTO,'YYYY-MM')
 ORDER BY prof, mes;

PROMPT === 4. EHF & RB convênio 0110 raw rows Feb (titular + dependente split?) ===
SELECT l.LANCPROFDEST prof, ROUND(l.LANNVALOR,2) net, SUBSTR(l.LANCHISTORICO,1,60) hist
  FROM FINANCE.LANCAMENTO l
 WHERE l.PCTCNUMEROCONTADEST='030.010.0110'
   AND l.LANCPROFDEST IN ('EHF','RB')
   AND l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01'
 ORDER BY prof, net DESC;

PROMPT === 5. Is 0150 flagged professional? and does it appear in GERENC_LANCAMENTORESUMO? ===
SELECT r.ID_CONTA, r.NOME_CONTA, ROUND(SUM(r.VALOR),2) tot, COUNT(*) n
  FROM LDESK.GERENC_LANCAMENTORESUMO r
 WHERE r.ID_CONTA IN ('030.010.0150','030.010.0160') AND r.ANO_MES='2026-02'
 GROUP BY r.ID_CONTA, r.NOME_CONTA;

EXIT
