-- probe_despesas_liquido.sql
-- UNLOCK CONFIRMED: CONTASPAGAR has CPGNVALORLIQUIDO (net) + CPGNVALORBRUTO/BASE
-- (gross). The workbook books LÍQUIDO. Desdobramento of lump payments (cartão,
-- plano, transitória) lives in CPDESDOBRAMENTO (DESCCONTADESTINO, DESNVALOR).
-- Reconstruct May institutional despesas by LÍQUIDO and compare to workbook
-- row-198 = 105.511,43. Dial in the exact recipe offline from this dump.
SET DEFINE OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET LONG 100000
SET TRIMOUT ON
SET FEEDBACK OFF
SET HEADING OFF
WHENEVER SQLERROR CONTINUE

PROMPT #A Direct CONTASPAGAR by conta (020/040), May: SUM liquido / base / bruto
SELECT 'A|'||cp.PCTCNUMEROCONTA
       ||'|liq='||TO_CHAR(ROUND(SUM(cp.CPGNVALORLIQUIDO),2))
       ||'|base='||TO_CHAR(ROUND(SUM(cp.CPGNVALORBASE),2))
       ||'|bruto='||TO_CHAR(ROUND(SUM(cp.CPGNVALORBRUTO),2))
       ||'|n='||COUNT(*)
  FROM FINANCE.CONTASPAGAR cp
 WHERE (cp.PCTCNUMEROCONTA LIKE '020.%' OR cp.PCTCNUMEROCONTA LIKE '040.%')
   AND cp.CPGDVECTO >= DATE '2026-05-01' AND cp.CPGDVECTO < DATE '2026-06-01'
 GROUP BY cp.PCTCNUMEROCONTA
 ORDER BY cp.PCTCNUMEROCONTA;

PROMPT #B CPDESDOBRAMENTO by conta destino (020/040), parent paid in May: SUM DESNVALOR
SELECT 'B|'||d.DESCCONTADESTINO
       ||'|desnvalor='||TO_CHAR(ROUND(SUM(d.DESNVALOR),2))
       ||'|setor='||NVL(MAX(d.DESCSETOR),'')
       ||'|n='||COUNT(*)
  FROM FINANCE.CPDESDOBRAMENTO d
  JOIN FINANCE.CONTASPAGAR cp
    ON cp.EMPNCOD = d.EMPNCOD AND cp.CPGCNUMEROPAGAR = d.CPGCNUMEROPAGAR
 WHERE (d.DESCCONTADESTINO LIKE '020.%' OR d.DESCCONTADESTINO LIKE '040.%')
   AND cp.CPGDVECTO >= DATE '2026-05-01' AND cp.CPGDVECTO < DATE '2026-06-01'
 GROUP BY d.DESCCONTADESTINO
 ORDER BY d.DESCCONTADESTINO;

PROMPT #C Does CPDESDOBRAMENTO carry a net vs gross? Dump the Ozai + a card desdobr sample
SELECT 'C|'||cp.PCTCNUMEROCONTA||'->'||d.DESCCONTADESTINO
       ||'|desnvalor='||TO_CHAR(ROUND(d.DESNVALOR,2))
       ||'|'||SUBSTR(REPLACE(NVL(d.DESCHISTORICO,' '),'|','/'),1,30)
  FROM FINANCE.CPDESDOBRAMENTO d
  JOIN FINANCE.CONTASPAGAR cp
    ON cp.EMPNCOD = d.EMPNCOD AND cp.CPGCNUMEROPAGAR = d.CPGCNUMEROPAGAR
 WHERE cp.CPGDVECTO >= DATE '2026-05-01' AND cp.CPGDVECTO < DATE '2026-06-01'
   AND (cp.PCTCNUMEROCONTA LIKE '200.%' OR UPPER(cp.CPGCHISTORICO) LIKE '%OZAI%')
 ORDER BY cp.PCTCNUMEROCONTA
 FETCH FIRST 40 ROWS ONLY;

PROMPT #D Ozai row: confirm CPGNVALORLIQUIDO = 8042.94
SELECT 'D|'||cp.PCTCNUMEROCONTA||'|liq='||TO_CHAR(cp.CPGNVALORLIQUIDO)
       ||'|base='||TO_CHAR(cp.CPGNVALORBASE)||'|bruto='||TO_CHAR(cp.CPGNVALORBRUTO)
  FROM FINANCE.CONTASPAGAR cp
 WHERE cp.CPGDVECTO >= DATE '2026-05-01' AND cp.CPGDVECTO < DATE '2026-06-01'
   AND UPPER(cp.CPGCHISTORICO) LIKE '%OZAI%';

PROMPT #END
EXIT
