-- Hunt: Vale Refeição (0100) + Vale Transporte (0220) for Feb 2026. The resumo
-- GERENC_LANCAMENTORESUMO returned NO rows for these accounts (in either
-- destination area or blank), yet the ledger has Contencioso Vale = 1.249,40.
-- Where do they live?  Read-only.
SET DEFINE OFF
SET PAGESIZE 400
SET LINESIZE 260
SET FEEDBACK ON
COL prof FORMAT A6
COL grupo FORMAT A20
COL hist FORMAT A45
WHENEVER SQLERROR CONTINUE

PROMPT === 1. LANCAMENTO 0100/0220 raw, Feb 2026 (all destination cols) ===
SELECT l.PCTCNUMEROCONTADEST conta, l.COD_ADVG sigla_advg, l.LANCPROFDEST prof,
       l.SIGLADEST cc, l.ID_GRUPOJURIDICODEST grupo,
       ROUND(l.LANNVALOR,2) net, SUBSTR(l.LANCHISTORICO,1,45) hist
  FROM FINANCE.LANCAMENTO l
 WHERE l.PCTCNUMEROCONTADEST IN ('030.010.0100','030.010.0220')
   AND l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01'
 ORDER BY conta;

PROMPT === 2. LANCAMENTO 0100/0220 aggregated by cc/grupo, Feb ===
SELECT l.PCTCNUMEROCONTADEST conta, l.SIGLADEST cc, l.ID_GRUPOJURIDICODEST grupo,
       ROUND(SUM(l.LANNVALOR),2) net, COUNT(*) n
  FROM FINANCE.LANCAMENTO l
 WHERE l.PCTCNUMEROCONTADEST IN ('030.010.0100','030.010.0220')
   AND l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01'
 GROUP BY l.PCTCNUMEROCONTADEST, l.SIGLADEST, l.ID_GRUPOJURIDICODEST
 ORDER BY conta;

PROMPT === 3. CONTASPAGAR 0100/0220 for Feb (maybe payable-side only) ===
SELECT cp.PCTCNUMEROCONTA conta, cp.COD_ADVG sigla,
       ROUND(SUM(cp.CPGNVALORBASE),2) base, COUNT(*) n
  FROM FINANCE.CONTASPAGAR cp
 WHERE cp.PCTCNUMEROCONTA IN ('030.010.0100','030.010.0220')
   AND cp.CPGDVECTO >= DATE '2026-02-01' AND cp.CPGDVECTO < DATE '2026-03-01'
 GROUP BY cp.PCTCNUMEROCONTA, cp.COD_ADVG
 ORDER BY conta;

PROMPT === 4. Anything mentioning "Vale" in histórico across ALL accounts, Feb ===
SELECT l.PCTCNUMEROCONTADEST conta, SUBSTR(l.LANCHISTORICO,1,50) hist,
       ROUND(SUM(l.LANNVALOR),2) net, COUNT(*) n
  FROM FINANCE.LANCAMENTO l
 WHERE UPPER(l.LANCHISTORICO) LIKE '%VALE%'
   AND l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01'
 GROUP BY l.PCTCNUMEROCONTADEST, SUBSTR(l.LANCHISTORICO,1,50)
 ORDER BY net DESC;

PROMPT === 5. Does resumo carry Vale accounts for ANY month/year? ===
SELECT r.ANO_MES, r.ID_CONTA, ROUND(SUM(r.VALOR),2) tot, COUNT(*) n
  FROM LDESK.GERENC_LANCAMENTORESUMO r
 WHERE r.ID_CONTA IN ('030.010.0100','030.010.0220')
   AND r.ANO_MES BETWEEN '2026-01' AND '2026-05'
 GROUP BY r.ANO_MES, r.ID_CONTA ORDER BY r.ANO_MES, r.ID_CONTA;

EXIT
