-- Probe v2: per-area recebimento via CASO -> AREAJURIDICA (receipt view has ID_CASO).
-- CAD_CASO.ID_AREAJURIDICA -> CAD_AREAJURIDICA.NOME. Read-only.
SET DEFINE OFF
SET PAGESIZE 200
SET LINESIZE 300
SET FEEDBACK OFF
WHENEVER SQLERROR CONTINUE
SELECT owner, table_name FROM ALL_TABLES WHERE owner IN ('LDESK','SSJR') AND table_name LIKE '%AREAJURIDICA%' ORDER BY owner, table_name;
SELECT column_name FROM ALL_TAB_COLUMNS WHERE owner='LDESK' AND table_name='CAD_AREAJURIDICA' ORDER BY column_id;
SELECT r.ANO_MES, NVL(a.NOME,'(sem area)') area, ROUND(SUM(r.VALOR1),2) total, COUNT(*) n FROM LDESK.GERENC_VW_POSFIN_RESULTREC r LEFT JOIN LDESK.CAD_CASO c ON c.ID_CASO=r.ID_CASO LEFT JOIN LDESK.CAD_AREAJURIDICA a ON a.ID_AREAJURIDICA=c.ID_AREAJURIDICA WHERE r.ANO_MES IN ('2026-01','2026-02') GROUP BY r.ANO_MES, a.NOME ORDER BY r.ANO_MES, total DESC;
EXIT
