-- probe_resultados_views.sql
-- VW_RESULTADO_MENSAL_DET is cash-basis (= our snapshot). The workbook uses a
-- DIFFERENT view. Candidates found via ALL_OBJECTS: VW_RESULTADOS, VW_RESULTADOS2,
-- VW_RESULTADOS3, VW_RESULTADOS3OF, plus DETALHERATEIO / CPDESDOBRAMENTO.
-- Goal: find the view whose May despesas total = 105.511,43 and Informática has
-- Suporte Totvs 2917.77 / Licenças 13700.31 (the workbook competência figures).
SET DEFINE OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET LONG 100000
SET TRIMOUT ON
SET FEEDBACK OFF
SET HEADING OFF
WHENEVER SQLERROR CONTINUE

PROMPT #A Columns of each VW_RESULTADOS* view (so we know how to query)
SELECT 'A|'||TABLE_NAME||'|'||COLUMN_NAME||'|'||DATA_TYPE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER='FINANCE' AND TABLE_NAME IN
   ('VW_RESULTADOS','VW_RESULTADOS2','VW_RESULTADOS3','VW_RESULTADOS3OF',
    'VW_DETALHERATEIOANOMES','DETALHERATEIOANOMES')
 ORDER BY TABLE_NAME, COLUMN_ID;

PROMPT #B CPDESDOBRAMENTO / CPDESDOBRAMENTOPG columns (the desdobramento tables)
SELECT 'B|'||TABLE_NAME||'|'||COLUMN_NAME||'|'||DATA_TYPE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER='FINANCE' AND TABLE_NAME IN ('CPDESDOBRAMENTO','CPDESDOBRAMENTOPG')
 ORDER BY TABLE_NAME, COLUMN_ID;

PROMPT #END
EXIT
