-- Probe: FINANCE.VW_RESULTADO_MENSAL family — a DRE report view with
-- CONTA1/2/3 + TITULO1/2/3 + NIVEL + SETOR + ORCAMENTO. This is the strongest
-- candidate to be the workbook's literal source: hierarchical account titles
-- (matching the workbook families) AND a budget column AND a SETOR (area).
-- Workbook Feb: Despesa Institucional total 95.047,39.
SET DEFINE OFF
SET PAGESIZE 3000
SET LINESIZE 320
SET FEEDBACK ON
COL titulo1 FORMAT A28
COL titulo2 FORMAT A28
COL titulo3 FORMAT A34
COL setor FORMAT A10
COL tipo FORMAT A6
WHENEVER SQLERROR CONTINUE

PROMPT === 1. VW_RESULTADO_MENSAL distinct TIPO + NIVEL + SETOR present, Feb ===
SELECT TIPO, NIVEL, SETOR, COUNT(*) n, ROUND(SUM(VALOR),2) total
  FROM FINANCE.VW_RESULTADO_MENSAL
 WHERE ANO_MES='2026-02'
 GROUP BY TIPO, NIVEL, SETOR
 ORDER BY TIPO, NIVEL, SETOR;

PROMPT === 2. VW_RESULTADO_MENSAL level-1/2 titles + values Feb (the DRE skeleton) ===
SELECT TIPO, NIVEL, TITULO1, TITULO2, ROUND(SUM(VALOR),2) total, ROUND(SUM(ORCAMENTO),2) orc
  FROM FINANCE.VW_RESULTADO_MENSAL
 WHERE ANO_MES='2026-02' AND NIVEL <= 2
 GROUP BY TIPO, NIVEL, TITULO1, TITULO2
 ORDER BY TIPO, NIVEL, TITULO1, TITULO2;

PROMPT === 3. VW_RESULTADO_MENSAL: sum of despesa-type (D) Feb — hit 95.047,39? ===
SELECT TIPO, ROUND(SUM(VALOR),2) total
  FROM FINANCE.VW_RESULTADO_MENSAL
 WHERE ANO_MES='2026-02'
 GROUP BY TIPO ORDER BY TIPO;

PROMPT === 4. VW_RESULTADO_MENSALCC: per-SETOR (centro custo) despesa Feb ===
SELECT SETOR, TIPO, ROUND(SUM(VALOR),2) total, COUNT(*) n
  FROM FINANCE.VW_RESULTADO_MENSALCC
 WHERE ANO_MES='2026-02'
 GROUP BY SETOR, TIPO ORDER BY TIPO, SETOR;

PROMPT === 5. VW_RESULTADO_MENSALCC: distinct SETOR codes (map to areas?) ===
SELECT DISTINCT SETOR FROM FINANCE.VW_RESULTADO_MENSALCC WHERE ANO_MES='2026-02' ORDER BY SETOR;

PROMPT === 6. VW_RESULTADO_MENSAL level-2 titles for TIPO=D (institutional families) Feb ===
-- Compare these titles+values to the workbook row-198 families (Ocupacao, etc.).
SELECT TITULO1, TITULO2, ROUND(SUM(VALOR),2) total
  FROM FINANCE.VW_RESULTADO_MENSAL
 WHERE ANO_MES='2026-02' AND TIPO='D'
 GROUP BY TITULO1, TITULO2 ORDER BY TITULO1, TITULO2;

EXIT
