-- probe_provisao.sql
-- Hunt the workbook's SMOOTHED Informática provisão values across the DB.
-- The workbook books flat monthly figures the cash ledger doesn't show:
--   Suporte Totvs 2917.77/mo, Suporte Informática 2040/mo, Licenças ~13700 (May).
-- If these live in a competência/provisão VIEW (not the cash LANCAMENTO), find it.
SET DEFINE OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET LONG 100000
SET TRIMOUT ON
SET FEEDBACK OFF
SET HEADING OFF
WHENEVER SQLERROR CONTINUE

PROMPT #A Exact-value hunt across VW_RESULTADO_MENSAL_DET (competencia view), all months
SELECT 'A|'||ANO_MES||'|'||NVL(CONTA3,'?')||'|'||NVL(TITULO3,'?')||'|'||NVL(SETOR,'')||'|'||TO_CHAR(ROUND(SUM(VALOR),2))
  FROM FINANCE.VW_RESULTADO_MENSAL_DET
 WHERE ANO_MES BETWEEN '2026-01' AND '2026-05'
 GROUP BY ANO_MES, CONTA3, TITULO3, SETOR
 HAVING ROUND(SUM(VALOR),2) IN (2917.77,2040,2040.00,13700.31,3387.47,2003.73)
 ORDER BY ANO_MES;

PROMPT #B Does a Totvs/Suporte value 2917.77 appear ANYWHERE in VW_RESULTADO_MENSAL_DET?
SELECT 'B|'||ANO_MES||'|'||TIPO||'|'||NVL(CONTA3,'?')||'|'||NVL(TITULO3,'?')||'|'||TO_CHAR(ROUND(SUM(VALOR),2))
  FROM FINANCE.VW_RESULTADO_MENSAL_DET
 WHERE ANO_MES BETWEEN '2026-01' AND '2026-05'
   AND (UPPER(TITULO3) LIKE '%TOTVS%' OR UPPER(TITULO3) LIKE '%SUPORTE%' OR UPPER(TITULO2) LIKE '%INFORM%')
 GROUP BY ANO_MES, TIPO, CONTA3, TITULO3
 ORDER BY ANO_MES, CONTA3;

PROMPT #C 020.040.0010 + 040.040.0030 monthly totals in VW (competencia) vs what we saw in cash
SELECT 'C|'||ANO_MES||'|'||CONTA3||'|'||TO_CHAR(ROUND(SUM(VALOR),2))
  FROM FINANCE.VW_RESULTADO_MENSAL_DET
 WHERE ANO_MES BETWEEN '2026-01' AND '2026-05'
   AND CONTA3 IN ('020.040.0010','040.040.0030','040.040.0010','040.040.0020')
 GROUP BY ANO_MES, CONTA3
 ORDER BY ANO_MES, CONTA3;

PROMPT #D List ALL distinct FINANCE views/tables with RESULTADO or PROVIS or COMPET in the name
SELECT 'D|'||OBJECT_TYPE||'|'||OBJECT_NAME
  FROM ALL_OBJECTS
 WHERE OWNER='FINANCE'
   AND (UPPER(OBJECT_NAME) LIKE '%RESULTADO%' OR UPPER(OBJECT_NAME) LIKE '%PROVIS%'
        OR UPPER(OBJECT_NAME) LIKE '%COMPET%' OR UPPER(OBJECT_NAME) LIKE '%AMORTIZ%'
        OR UPPER(OBJECT_NAME) LIKE '%RATEIO%' OR UPPER(OBJECT_NAME) LIKE '%DRE%')
 ORDER BY OBJECT_NAME;

PROMPT #E Totvs/Juritis payments in CONTASPAGAR with future competencia (accrual spread?)
SELECT 'E|'||TO_CHAR(cp.CPGDVECTO,'YYYY-MM')||'|'||cp.PCTCNUMEROCONTA||'|'||SUBSTR(REPLACE(NVL(cp.CPGCHISTORICO,' '),'|','/'),1,40)||'|'||TO_CHAR(ROUND(cp.CPGNVALORBASE,2))
  FROM FINANCE.CONTASPAGAR cp
 WHERE (UPPER(cp.CPGCHISTORICO) LIKE '%TOTVS%' OR UPPER(cp.CPGCHISTORICO) LIKE '%JURITIS%' OR UPPER(cp.CPGCHISTORICO) LIKE '%LICEN%' OR UPPER(cp.CPGCHISTORICO) LIKE '%AZURE%')
   AND cp.CPGDVECTO >= DATE '2026-01-01' AND cp.CPGDVECTO < DATE '2026-06-01'
 ORDER BY cp.CPGDVECTO;

PROMPT #END
EXIT
