-- probe_vale_lanc.sql
-- CORRECTED SOURCE: the Vale lives in FINANCE.LANCAMENTO (destination side), NOT in
-- CONTASPAGAR and NOT in the summarised resumo. probe_vale_hunt.sql proved the Vale
-- postings are on PCTCNUMEROCONTADEST 030.010.0100 (Refeição) / 030.010.0220
-- (Transporte), dated by LANDDATA, with a destination cost-center (SIGLADEST) and
-- area group (ID_GRUPOJURIDICODEST). The ADM slice is the one whose group is NOT one
-- of the three areas (Contencioso/Econômico/Arbitragem) — that ADM Vale is what the
-- workbook puts in Salários Administração.
--
-- Workbook Vale-ADM targets (Ref / Transp), Jan..Mai:
--   Ref:    829.80 / 1014.20 / 2766.00 / 2766.00 / 2719.90
--   Transp: 298.16 /  337.68 / 1217.22 /  655.36 /  607.04
SET DEFINE OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET TRIMOUT ON
SET FEEDBACK OFF
SET HEADING OFF
WHENEVER SQLERROR CONTINUE

PROMPT #A Vale postings (030.010.0100/0220) Jan..Mai, per month/conta/cc/grupo
SELECT 'A|'||TO_CHAR(l.LANDDATA,'YYYY-MM')
       ||'|'||l.PCTCNUMEROCONTADEST
       ||'|cc='||NVL(l.SIGLADEST,'?')
       ||'|grp='||NVL(TO_CHAR(l.ID_GRUPOJURIDICODEST),'?')
       ||'|'||NVL(MAX(g.NOME),'(sem area)')
       ||'|'||TO_CHAR(ROUND(SUM(l.LANNVALOR),2))||'|n='||COUNT(*)
  FROM FINANCE.LANCAMENTO l
  LEFT JOIN LDESK.CAD_GRUPOJURIDICO g ON g.ID_GRUPOJURIDICO = l.ID_GRUPOJURIDICODEST
 WHERE l.PCTCNUMEROCONTADEST IN ('030.010.0100','030.010.0220')
   AND l.LANDDATA >= DATE '2026-01-01' AND l.LANDDATA < DATE '2026-06-01'
 GROUP BY TO_CHAR(l.LANDDATA,'YYYY-MM'), l.PCTCNUMEROCONTADEST,
          l.SIGLADEST, l.ID_GRUPOJURIDICODEST
 ORDER BY TO_CHAR(l.LANDDATA,'YYYY-MM'), l.PCTCNUMEROCONTADEST, l.SIGLADEST;

PROMPT #B Any LANCAMENTO with VALE/REFEI/TRANSP in historico, Jan..Mai, per conta/grupo
SELECT 'B|'||TO_CHAR(l.LANDDATA,'YYYY-MM')
       ||'|'||NVL(l.PCTCNUMEROCONTADEST,'?')
       ||'|cc='||NVL(l.SIGLADEST,'?')
       ||'|'||NVL(MAX(g.NOME),'(sem area)')
       ||'|'||SUBSTR(REPLACE(NVL(MAX(l.LANCHISTORICO),' '),'|','/'),1,34)
       ||'|'||TO_CHAR(ROUND(SUM(l.LANNVALOR),2))
  FROM FINANCE.LANCAMENTO l
  LEFT JOIN LDESK.CAD_GRUPOJURIDICO g ON g.ID_GRUPOJURIDICO = l.ID_GRUPOJURIDICODEST
 WHERE ( UPPER(l.LANCHISTORICO) LIKE '%VALE%'
      OR UPPER(l.LANCHISTORICO) LIKE '%REFEI%'
      OR UPPER(l.LANCHISTORICO) LIKE '%TRANSP%' )
   AND l.LANDDATA >= DATE '2026-01-01' AND l.LANDDATA < DATE '2026-06-01'
 GROUP BY TO_CHAR(l.LANDDATA,'YYYY-MM'), l.PCTCNUMEROCONTADEST, l.SIGLADEST
 ORDER BY TO_CHAR(l.LANDDATA,'YYYY-MM'), l.PCTCNUMEROCONTADEST, l.SIGLADEST;

PROMPT #C Monthly Vale total (030.010.0100/0220) split by area-vs-ADM group
SELECT 'C|'||TO_CHAR(l.LANDDATA,'YYYY-MM')
       ||'|'||l.PCTCNUMEROCONTADEST
       ||'|'||TO_CHAR(ROUND(SUM(l.LANNVALOR),2))
  FROM FINANCE.LANCAMENTO l
 WHERE l.PCTCNUMEROCONTADEST IN ('030.010.0100','030.010.0220')
   AND l.LANDDATA >= DATE '2026-01-01' AND l.LANDDATA < DATE '2026-06-01'
 GROUP BY TO_CHAR(l.LANDDATA,'YYYY-MM'), l.PCTCNUMEROCONTADEST
 ORDER BY TO_CHAR(l.LANDDATA,'YYYY-MM'), l.PCTCNUMEROCONTADEST;

PROMPT #END
EXIT
