-- probe_vale_find.sql
-- 030.010.0100/0220 have NO rows in LANCAMENTO by LANDDATA Jan..Mai, and there is NO
-- ID_GRUPOJURIDICODEST column (area is carried by SIGLADEST / LANCPROFDEST). So find
-- the Vale purely by historico across ALL destination accounts, and check BOTH date
-- columns (LANDDATA vs LANDDATADESP) in case competence differs from posting date.
-- Confirmed LANCAMENTO cols used: PCTCNUMEROCONTADEST, SIGLADEST, LANCPROFDEST,
-- LANCHISTORICO, LANNVALOR, LANDDATA, LANDDATADESP.
--
-- Target ADM Vale (Ref+Transp) Jan..Mai: 1127.96/1351.88/3983.22/3421.36/3326.94
SET DEFINE OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET TRIMOUT ON
SET FEEDBACK OFF
SET HEADING OFF
WHENEVER SQLERROR CONTINUE

PROMPT #A Vale by historico across ALL accounts, by LANDDATA, per month/conta/sigla
SELECT 'A|'||TO_CHAR(l.LANDDATA,'YYYY-MM')
       ||'|'||NVL(l.PCTCNUMEROCONTADEST,'?')
       ||'|cc='||NVL(l.SIGLADEST,'?')
       ||'|prof='||NVL(l.LANCPROFDEST,'?')
       ||'|'||SUBSTR(REPLACE(NVL(MAX(l.LANCHISTORICO),' '),'|','/'),1,34)
       ||'|'||TO_CHAR(ROUND(SUM(l.LANNVALOR),2))
  FROM FINANCE.LANCAMENTO l
 WHERE ( UPPER(l.LANCHISTORICO) LIKE '%VALE%'
      OR UPPER(l.LANCHISTORICO) LIKE '%REFEI%'
      OR UPPER(l.LANCHISTORICO) LIKE '%TRANSPORTE%' )
   AND l.LANDDATA >= DATE '2026-01-01' AND l.LANDDATA < DATE '2026-06-01'
 GROUP BY TO_CHAR(l.LANDDATA,'YYYY-MM'), l.PCTCNUMEROCONTADEST, l.SIGLADEST, l.LANCPROFDEST
 ORDER BY TO_CHAR(l.LANDDATA,'YYYY-MM'), l.PCTCNUMEROCONTADEST, l.SIGLADEST;

PROMPT #B Vale by historico, by LANDDATADESP (despesa/competence date) instead
SELECT 'B|'||TO_CHAR(l.LANDDATADESP,'YYYY-MM')
       ||'|'||NVL(l.PCTCNUMEROCONTADEST,'?')
       ||'|cc='||NVL(l.SIGLADEST,'?')
       ||'|'||TO_CHAR(ROUND(SUM(l.LANNVALOR),2))
  FROM FINANCE.LANCAMENTO l
 WHERE ( UPPER(l.LANCHISTORICO) LIKE '%VALE%'
      OR UPPER(l.LANCHISTORICO) LIKE '%REFEI%'
      OR UPPER(l.LANCHISTORICO) LIKE '%TRANSPORTE%' )
   AND l.LANDDATADESP >= DATE '2026-01-01' AND l.LANDDATADESP < DATE '2026-06-01'
 GROUP BY TO_CHAR(l.LANDDATADESP,'YYYY-MM'), l.PCTCNUMEROCONTADEST, l.SIGLADEST
 ORDER BY TO_CHAR(l.LANDDATADESP,'YYYY-MM'), l.PCTCNUMEROCONTADEST, l.SIGLADEST;

PROMPT #C Distinct destination accounts that EVER carry a Vale historico (any date)
SELECT 'C|'||NVL(l.PCTCNUMEROCONTADEST,'?')||'|'||TO_CHAR(COUNT(*))
  FROM FINANCE.LANCAMENTO l
 WHERE ( UPPER(l.LANCHISTORICO) LIKE '%VALE%'
      OR UPPER(l.LANCHISTORICO) LIKE '%REFEI%' )
   AND l.LANDDATA >= DATE '2026-01-01' AND l.LANDDATA < DATE '2026-06-01'
 GROUP BY l.PCTCNUMEROCONTADEST
 ORDER BY l.PCTCNUMEROCONTADEST;

PROMPT #D What accounts EXIST at all in LANCAMENTO for Feb (sanity: is table populated by LANDDATA?)
SELECT 'D|feb_rows='||TO_CHAR(COUNT(*))
  FROM FINANCE.LANCAMENTO l
 WHERE l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01';

PROMPT #END
EXIT
