-- probe_aluguel_credito.sql
-- LAST despesas gap: Ocupação +3.247,07 = the aluguel sublet credit that abates
-- rent (bruto 27.477,67 -> workbook 24.230,60). Hunt it. Target ~3.247 (or the
-- exact 27477.67 - 24230.60 = 3247.07). "Está no sistema" per Adriana.
SET DEFINE OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET LONG 100000
SET TRIMOUT ON
SET FEEDBACK OFF
SET HEADING OFF
WHENEVER SQLERROR CONTINUE

PROMPT #A Exact-value hunt: any LANCAMENTO ~3247 in May (the credit), any conta
SELECT 'A|'||NVL(l.PCTCNUMEROCONTADEST,'?')||'|'||TO_CHAR(ROUND(l.LANNVALOR,2))||'|'||SUBSTR(REPLACE(NVL(l.LANCHISTORICO,' '),'|','/'),1,50) linha
  FROM FINANCE.LANCAMENTO l
 WHERE l.LANDDATA >= DATE '2026-05-01' AND l.LANDDATA < DATE '2026-06-01'
   AND ROUND(ABS(l.LANNVALOR),2) BETWEEN 3200 AND 3300
 ORDER BY linha;

PROMPT #B Receitas/creditos touching Ocupacao or aluguel histórico, May (any sign)
SELECT 'B|'||NVL(l.PCTCNUMEROCONTADEST,'?')||'|'||NVL(l.PCTCNUMEROCONTAORG,'?')||'|'||TO_CHAR(ROUND(l.LANNVALOR,2))||'|'||SUBSTR(REPLACE(NVL(l.LANCHISTORICO,' '),'|','/'),1,45) linha
  FROM FINANCE.LANCAMENTO l
 WHERE l.LANDDATA >= DATE '2026-05-01' AND l.LANDDATA < DATE '2026-06-01'
   AND (UPPER(l.LANCHISTORICO) LIKE '%ALUGU%' OR UPPER(l.LANCHISTORICO) LIKE '%LACERDA%'
        OR UPPER(l.LANCHISTORICO) LIKE '%LOCA%' OR UPPER(l.LANCHISTORICO) LIKE '%CEDID%'
        OR UPPER(l.LANCHISTORICO) LIKE '%ESPACO%' OR UPPER(l.LANCHISTORICO) LIKE '%SALA%')
 ORDER BY linha;

PROMPT #C CPDESDOBRAMENTO rows to 020.010.0010 (aluguel), May, with sign + histórico
SELECT 'C|'||TO_CHAR(ROUND(d.DESNVALOR,2))||'|'||SUBSTR(REPLACE(NVL(d.DESCHISTORICO,' '),'|','/'),1,50) linha
  FROM FINANCE.CPDESDOBRAMENTO d
  JOIN FINANCE.CONTASPAGAR cp ON cp.EMPNCOD=d.EMPNCOD AND cp.CPGCNUMEROPAGAR=d.CPGCNUMEROPAGAR
 WHERE d.DESCCONTADESTINO='020.010.0010'
   AND cp.CPGDVECTO >= DATE '2026-05-01' AND cp.CPGDVECTO < DATE '2026-06-01'
 ORDER BY linha;

PROMPT #D The aluguel CONTASPAGAR row itself: full detail (is there a credit/abatimento field?)
SELECT 'D|pagar='||cp.CPGCNUMEROPAGAR||'|liq='||TO_CHAR(cp.CPGNVALORLIQUIDO)||'|base='||TO_CHAR(cp.CPGNVALORBASE)||'|bruto='||TO_CHAR(cp.CPGNVALORBRUTO)||'|desp='||TO_CHAR(cp.CPGNDESPESA) linha
  FROM FINANCE.CONTASPAGAR cp
 WHERE cp.PCTCNUMEROCONTA='020.010.0010'
   AND cp.CPGDVECTO >= DATE '2026-05-01' AND cp.CPGDVECTO < DATE '2026-06-01'
 ORDER BY linha;

PROMPT #E Any RECEITA account (010.* or a credit) with ~3247 or aluguel-related, May
SELECT 'E|'||r.ID_CONTA||'|'||MAX(r.NOME_CONTA)||'|'||TO_CHAR(ROUND(SUM(r.VALOR),2)) linha
  FROM LDESK.GERENC_LANCAMENTORESUMO r
 WHERE r.ANO_MES='2026-05'
   AND (UPPER(r.NOME_CONTA) LIKE '%ALUGU%' OR UPPER(r.NOME_CONTA) LIKE '%LOCA%'
        OR UPPER(r.NOME_CONTA) LIKE '%CEDID%' OR UPPER(r.NOME_CONTA) LIKE '%RESSARC%'
        OR UPPER(r.NOME_CONTA) LIKE '%SUBLOC%')
 GROUP BY r.ID_CONTA
 ORDER BY linha;

PROMPT #END
EXIT
