-- probe_despesas_close.sql
-- Close the last 4 institutional families (May) after the líquido+desdobramento win.
-- Remaining vs workbook: Ocupação +3247 (sublet credit), Informática -2166
-- (Licenças net lines), Gestão do Conhecimento -1600 (Cursos 030.010.0180),
-- Despesas Gerais +3190 (card competência). Workbook row-198 = 105.511,43.
SET DEFINE OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET LONG 100000
SET TRIMOUT ON
SET FEEDBACK OFF
SET HEADING OFF
WHENEVER SQLERROR CONTINUE

PROMPT #A ALUGUEL sublet credit: any NEGATIVE / credit posting or ressarcimento on Ocupacao, May
-- The office sublets space; the reimbursement (~R$3k) abates aluguel (workbook 24.230,60
-- vs bruto 27.477,67). Look for credits/receipts touching 020.010.0010 or a sublocacao histórico.
SELECT 'A1|'||NVL(l.PCTCNUMEROCONTADEST,'?')||'|'||SUBSTR(REPLACE(NVL(l.LANCHISTORICO,' '),'|','/'),1,45)||'|'||TO_CHAR(ROUND(l.LANNVALOR,2))
  FROM FINANCE.LANCAMENTO l
 WHERE l.LANDDATA >= DATE '2026-05-01' AND l.LANDDATA < DATE '2026-06-01'
   AND (UPPER(l.LANCHISTORICO) LIKE '%SUBLOC%' OR UPPER(l.LANCHISTORICO) LIKE '%RESSARC%'
        OR UPPER(l.LANCHISTORICO) LIKE '%CESS%ESPACO%' OR UPPER(l.LANCHISTORICO) LIKE '%LOCA%'
        OR (l.PCTCNUMEROCONTADEST='020.010.0010' AND l.LANNVALOR < 0))
 ORDER BY 1;

PROMPT #A2 CPDESDOBRAMENTO rows hitting 020.010.0010 (aluguel) May - any credit slice?
SELECT 'A2|'||d.DESCCONTADESTINO||'|'||TO_CHAR(ROUND(d.DESNVALOR,2))||'|'||SUBSTR(REPLACE(NVL(d.DESCHISTORICO,' '),'|','/'),1,40)
  FROM FINANCE.CPDESDOBRAMENTO d
  JOIN FINANCE.CONTASPAGAR cp ON cp.EMPNCOD=d.EMPNCOD AND cp.CPGCNUMEROPAGAR=d.CPGCNUMEROPAGAR
 WHERE d.DESCCONTADESTINO='020.010.0010'
   AND cp.CPGDVECTO >= DATE '2026-05-01' AND cp.CPGDVECTO < DATE '2026-06-01'
 ORDER BY 2;

PROMPT #B LICENCAS 040.040.0030 - ALL May CONTASPAGAR net lines (líquido) + base
SELECT 'B|'||cp.CPGCNUMEROPAGAR||'|liq='||TO_CHAR(ROUND(cp.CPGNVALORLIQUIDO,2))||'|base='||TO_CHAR(ROUND(cp.CPGNVALORBASE,2))||'|'||SUBSTR(REPLACE(NVL(cp.CPGCHISTORICO,' '),'|','/'),1,38)
  FROM FINANCE.CONTASPAGAR cp
 WHERE cp.PCTCNUMEROCONTA='040.040.0030'
   AND cp.CPGDVECTO >= DATE '2026-05-01' AND cp.CPGDVECTO < DATE '2026-06-01'
 ORDER BY cp.CPGNVALORLIQUIDO DESC;

PROMPT #B2 040.040.0030 via CPDESDOBRAMENTO (card-sourced licença slices) May
SELECT 'B2|'||TO_CHAR(ROUND(d.DESNVALOR,2))||'|'||SUBSTR(REPLACE(NVL(d.DESCHISTORICO,' '),'|','/'),1,42)
  FROM FINANCE.CPDESDOBRAMENTO d
  JOIN FINANCE.CONTASPAGAR cp ON cp.EMPNCOD=d.EMPNCOD AND cp.CPGCNUMEROPAGAR=d.CPGCNUMEROPAGAR
 WHERE d.DESCCONTADESTINO='040.040.0030'
   AND cp.CPGDVECTO >= DATE '2026-05-01' AND cp.CPGDVECTO < DATE '2026-06-01'
 ORDER BY 1;

PROMPT #C CURSOS 030.010.0180 May (net) - the Gestao do Conhecimento carve-out
SELECT 'C|'||cp.PCTCNUMEROCONTA||'|liq='||TO_CHAR(ROUND(SUM(cp.CPGNVALORLIQUIDO),2))||'|base='||TO_CHAR(ROUND(SUM(cp.CPGNVALORBASE),2))||'|n='||COUNT(*)
  FROM FINANCE.CONTASPAGAR cp
 WHERE cp.PCTCNUMEROCONTA='030.010.0180'
   AND cp.CPGDVECTO >= DATE '2026-05-01' AND cp.CPGDVECTO < DATE '2026-06-01'
 GROUP BY cp.PCTCNUMEROCONTA;

PROMPT #D Despesas Gerais 020.030.0020: split direct vs card, by DESDDATADESP competencia
-- The Claude 2166.53 + Mercado Livre may be a different competencia month. Show DESDDATADESP.
SELECT 'D|'||d.DESCCONTADESTINO||'|'||TO_CHAR(ROUND(d.DESNVALOR,2))||'|desp='||TO_CHAR(d.DESDDATADESP,'YYYY-MM-DD')||'|'||SUBSTR(REPLACE(NVL(d.DESCHISTORICO,' '),'|','/'),1,30)
  FROM FINANCE.CPDESDOBRAMENTO d
  JOIN FINANCE.CONTASPAGAR cp ON cp.EMPNCOD=d.EMPNCOD AND cp.CPGCNUMEROPAGAR=d.CPGCNUMEROPAGAR
 WHERE d.DESCCONTADESTINO='020.030.0020'
   AND cp.CPGDVECTO >= DATE '2026-05-01' AND cp.CPGDVECTO < DATE '2026-06-01'
 ORDER BY 2;

PROMPT #END
EXIT
