-- Probe: the per-lawyer key for team-cost accounts that CONTASPAGAR does NOT carry
-- (Convênio 030.010.0110, INSS 030.010.0050, and the small lines) is
-- LANCAMENTO.LANCPROFDEST (destination professional), confirmed by probe6 §3.
-- Pull per-(LANCPROFDEST, account) values so we can fold ALL Custo-equipe
-- components to areas. Read-only, Feb 2026.
SET DEFINE OFF
SET PAGESIZE 1000
SET LINESIZE 320
SET FEEDBACK ON
COL prof FORMAT A8
COL conta FORMAT A16
WHENEVER SQLERROR CONTINUE

PROMPT === 1. Per (LANCPROFDEST, account) NET for ALL 030.010.* — the full component matrix ===
SELECT l.LANCPROFDEST AS prof, l.PCTCNUMEROCONTADEST AS conta,
       ROUND(SUM(l.LANNVALOR),2) net_valor, COUNT(*) n
  FROM FINANCE.LANCAMENTO l
 WHERE l.PCTCNUMEROCONTADEST LIKE '030.010.%'
   AND l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01'
 GROUP BY l.LANCPROFDEST, l.PCTCNUMEROCONTADEST
 ORDER BY l.LANCPROFDEST, l.PCTCNUMEROCONTADEST;

PROMPT === 2. Each lawyer's HOME area (SIGLADEST from their distribuição row 0010) ===
PROMPT     Use to place convênio/INSS (which have no SIGLADEST) into the right area.
SELECT l.LANCPROFDEST AS prof, l.SIGLADEST AS cc, ROUND(SUM(l.LANNVALOR),2) v
  FROM FINANCE.LANCAMENTO l
 WHERE l.PCTCNUMEROCONTADEST='030.010.0010'
   AND l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01'
 GROUP BY l.LANCPROFDEST, l.SIGLADEST
 ORDER BY l.LANCPROFDEST;

PROMPT === 3. Convênio 0110 & INSS 0050 per lawyer (NET) — the previously-blank accounts ===
SELECT l.LANCPROFDEST AS prof, l.PCTCNUMEROCONTADEST AS conta,
       ROUND(SUM(l.LANNVALOR),2) net_valor
  FROM FINANCE.LANCAMENTO l
 WHERE l.PCTCNUMEROCONTADEST IN ('030.010.0110','030.010.0050')
   AND l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01'
 GROUP BY l.LANCPROFDEST, l.PCTCNUMEROCONTADEST
 ORDER BY l.PCTCNUMEROCONTADEST, l.LANCPROFDEST;

PROMPT === 4. Home-area map from CAD_PROFISSIONAL (sigla -> grupo) for ALL these lawyers ===
SELECT p.SIGLA, g.NOME AS grupo
  FROM LDESK.CAD_PROFISSIONAL p
  LEFT JOIN LDESK.CAD_GRUPOJURIDICO g ON g.ID_GRUPOJURIDICO=p.ID_GRUPOJURIDICO
 WHERE p.SIGLA IN ('AM','ASG','BBX','BMP','DC','EHF','EMC','FSM','IAC','JGS','JVO','MV','RB')
 ORDER BY p.SIGLA;

PROMPT === 5. Grand total ALL 030.010.* NET (ties to 216.954 ledger Custo equipe?) ===
SELECT ROUND(SUM(l.LANNVALOR),2) total_net, COUNT(*) n
  FROM FINANCE.LANCAMENTO l
 WHERE l.PCTCNUMEROCONTADEST LIKE '030.010.%'
   AND l.LANDDATA >= DATE '2026-02-01' AND l.LANDDATA < DATE '2026-03-01';

EXIT
